# Generated by Django 2.1 on 2018-08-10 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='用户的唯一id，pk', primary_key=True, serialize=False, verbose_name='用户的id')),
                ('user_name', models.TextField(help_text='用户名', verbose_name='用户名')),
                ('user_password', models.TextField(help_text='密码', verbose_name='密码')),
                ('user_info', models.TextField(blank=True, help_text='用户详细信息', verbose_name='介绍')),
            ],
        ),
    ]
