# Generated by Django 2.1 on 2018-08-10 07:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('todo_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='todo的唯一id，pk', primary_key=True, serialize=False, verbose_name='一个todo的id')),
                ('todo_content', models.TextField(help_text='todo的内容', verbose_name='内容')),
                ('todo_tag', models.TextField(default='今天', help_text='todo的标签', verbose_name='标签')),
                ('todo_complete', models.BooleanField(default=False, help_text='todo是否被标记为完成', verbose_name='是否完成')),
                ('todo_create_at', models.DateTimeField(auto_now_add=True, help_text='todo创建的时间戳', verbose_name='创建时间戳')),
                ('todo_update_at', models.DateTimeField(auto_now=True, help_text='每次数据修改的时间戳', verbose_name='更新时间戳')),
                ('todo_in_project', models.ForeignKey(help_text='一个todo所属的项目', on_delete=django.db.models.deletion.CASCADE, to='projects.Projects', verbose_name='所属项目')),
                ('todo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
    ]
